### ISSUE TITLE
Setup mlflow configuration when context is loaded

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#124]
## Description

When I call load_context() interactively, the configuration of the `mlflow.yml` is:
- not accessible through a context attributes
- not set up (especially, the mlflow tracking uri is not set)

## Context

I always struggle when i want to use the configuration in the `mlflow.yml` interactively. This makes experimentation & debugging harder.

## Possible Implementation

For now, I can't see how it is possible to modify the context object to add attributes. We can eventually add some to the catalog with the `after_catalog_created` hook, but the configuration should not be tied to the catalog execution.

**Comment by takikadiri** [comment]
I understand the point, but to my knowledge  the kedro context do not manage plugins properties, he just use them to supercharge his own properties (catalog, params, pipelines)

It isn't sufficient for you to get the config by calling the `get_mlflow_config` of kedro_mlflow ?
```
context = load_context(Path.cwd())
mlflow_config = get_mlflow_config(context)
```

**Comment by Galileo-Galilei** [comment]
The current implementation seems indeed satisfying enough (with ``kedro>=0.17`` and the a ``KedroSession`` activated, it can be simplified to 
```python
from kedro_mlflow.framework.context
mlflow_config=get_mlflow_config()
mlflow_config.setup()
```

However, we should setup automatically the configuration  for jupyter, through the ``%reload_kedro`` line magic.
