### ISSUE TITLE
Allow tracking to `databricks` URI

### ISSUE THREAD

**Issue by nblumoe** [Galileo-Galilei/kedro-mlflow#248]
## Description
We would like to track to a Databricks managed MLflow tracking server. This should be possible by setting the `mlflow_tracking_uri` to `databricks` (see [here](https://mlflow.org/docs/latest/tracking.html#where-runs-are-recorded))

kedro-mlfow will instead use a local, relative directory `./databricks` to track the metrics.

## Context
This would allow to integrate kedro-mlflow with the popular Databricks platform, more specifically the managed MLflow they offer.

## Possible Implementation
I don't know enough about the implementation to give recommendations. Maybe there needs to be a conditional not to interpret `databricks` as a relative path as it seems to be a reserved word for the tracking URIs?

## Possible Alternatives
As an alternative, it seems possible to use `databricks://<PROFILE>` as the tracking URI, but this requires to have such a profile in the first place.

**Comment by Galileo-Galilei** [comment]
Hello @nblumoe, thank you very much for reporting this bug. Would you mind checking if this branch fixes it for you?

```bash
pip uninstall kedro-mlflow
pip install git+https://github.com/Galileo-Galilei/kedro-mlflow.git@bug/mtu-databricks
```
When you confirm it is ok, I'll deploy the bugfix to PyPI.
