### ISSUE TITLE
Discrepancy between description and image

### ISSUE THREAD

**Issue by inseokson** [Galileo-Galilei/kedro-mlflow#302]
## Description

I found descriptions doesn't match some images in tutorial. 😃  In [Introduction > First steps with the plugin](https://kedro-mlflow.readthedocs.io/en/latest/source/03_getting_started/02_first_steps.html#first-steps-with-the-plugin), `mlflow.yml` file is said to be in `conf/local` in descriptions, but it is shown in `conf/base` in images. 

<img width="674" alt="screenshot" src="https://user-images.githubusercontent.com/48181337/163910188-32f329f9-ea55-4cff-8ee6-12ab9dd3e3a0.png">

**Comment by Galileo-Galilei** [comment]
Hi, thank you very much for the report, I'll fix it soon! For the record, you can specify the environment you want with ``kedro mlflow init --env=<your-env>`` command.
