### ISSUE TITLE
Add possibility to export mlflow environment variables in mlflow.yml

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#31]
This is required in #15 but is a more general need. Interactions with credentials must be designed.

**Comment by kaemo** [comment]
@Galileo-Galilei what do you mean by exporting MLflow environmental variables in `mlflow.yml`? Could we keep it consistent with MLflow and Kedro and use `.env`? It's already loaded by Kedro by default (I use it to configure `PYTHONPATH` for [debugging in VSCode](https://kedro.readthedocs.io/en/stable/09_development/01_set_up_vscode.html?highlight=.env#debugging).

**Comment by Galileo-Galilei** [comment]
Yes, sure. Actually, I am not a big fan (to say the least) of having a proprietary config  file so I amtotaly in favor of reusing what already exists. This issue is left open to keep track to the need to refactor the `mlflow.yml` file and the associated documentation.
