### ISSUE TITLE
Spell miss on Documentation?

### ISSUE THREAD

**Issue by gepuro** [Galileo-Galilei/kedro-mlflow#347]
## Description

I found the spell miss on https://github.com/Galileo-Galilei/kedro-mlflow/blob/master/docs/source/05_pipeline_serving/01_mlflow_models.md.

## Context

```
a MLModel file which is a configuration file to indicate to mlflow how to load thde model. 
```

means

```
a MLModel file which is a configuration file to indicate to mlflow how to load the model. 
```
?

I guess "thde model" is wrong.

## Steps to Reproduce

You can find it on https://github.com/Galileo-Galilei/kedro-mlflow/blob/master/docs/source/05_pipeline_serving/01_mlflow_models.md .

## Expected Result

```
a MLModel file which is a configuration file to indicate to mlflow how to load the model. 
```

## Actual Result

```
a MLModel file which is a configuration file to indicate to mlflow how to load thde model. 
```

on Document.

## Your Environment

I found it on https://kedro-mlflow.readthedocs.io/en/stable/source/05_pipeline_serving/01_mlflow_models.html.

## Does the bug also happen with the last version on master?

This documentation is latest.

**Comment by Galileo-Galilei** [comment]
Hi @gepuro, thank you very much for the correction, I'll fix it. For little spelling errors in the doc, feel free to edit directly on github and open a PR directly without creating an issue first!
