### ISSUE TITLE
Add support for authorization with expiring tokens

### ISSUE THREAD

**Issue by marrrcin** [Galileo-Galilei/kedro-mlflow#357]
## Description
In many of our integrations we deploy MLflow instances behind some authorization methods, is most cases - an OAuth2.0. Secured MLflow instances require HTTP requests to have the `Authorization: Bearer <token>` header.
Now, your plugin does a great job with the `server.credentials`, but it does not play well with tokens that are short-lived (e.g. 1h), which might expire during the execution (e.g. long running training job).

MLflow itself does expose the `mlflow.request_header_provider` plugin entrypoint (https://github.com/mlflow/mlflow/blob/master/mlflow/tracking/request_header/abstract_request_header_provider.py#L4), but it slightly collides with the usual use case - the ML project is not a Python package directly and it does not have `setup.py` which is required for the MLflow's plugin system to work.

## Context
Commercial deployments of MLflow in almost 100% cases are secured by some kind of authorization mechanism.

## Possible Implementation
Right now, we can attach our custom `request_header_provider` by accessing private field in MLflow and calling `register` with our implementation. We need to call it before kedro-mlflow hook, so we ended up with "disabling" hook for kedro-mlflow and then manually adding it in the project's `settings` after our `request_header_provider`.

```python
 from mlflow.tracking.request_header.registry import (
     _request_header_provider_registry,
 )
_request_header_provider_registry.register(OurCustomClass())
```

but it seems really "hacky".

I was wondering if you have any other ideas how this can be integrated into Kedro-MLflow? Maybe the plugin could expose some interface to dynamically (configurable in-project) provide the authorization headers to the requests? In a way, kedro-mlflow could have "always attached" `request_header_provider` which would act as a proxy for in-project configuration.

## Possible Alternatives
Ask `mlflow` to expose the header provider plugin in "dynamic" way, rather than only `setup.py`'s entrypoint.

**Comment by Galileo-Galilei** [comment]
Hi @marrrcin, thank you for the very clear issue. I was not aware of this authentication ability, but htis is easy to implement on the kedro-mlflow side. I'll push a demo branch soon so you can try it out. 

I think we can configure it through ``mlflow.yml``:

```yaml
#mlflow.yml

server: 
   request_header_provider: path.to.your.customclass
```

But I am worried by two things: 
- we use a private mlflow method, which does not seem right
- mlflow should expose a better public API (either with a public method, or with an entrypoint to automatically register your class). Would you mind checking on their side if there is a better way to do this? Since they are likely to implement it much slower than I can do, i agree to do it in kedro-mlflow, but I won't support too complicated use cases.

**Comment by marrrcin** [comment]
Hi @Galileo-Galilei, thanks for you interest in this!
I'm looking forward to see this in action.
In the meantime, I've actually implemented this in one of our plugins (because I needed the solution ASAP), you can check it out here: https://github.com/getindata/kedro-vertexai/pull/75/files . The idea there is the following - in the plugin, I'm declaring my "official" mlflow plugin implementation for the `request_header_provider`. This implementation is a singleton, which gets initialized (optionally) in `after_context_created` hook, in which I'm taking the plugin's config (VerexAI plugin) to construct custom header provider and attach it dynamically to the singleton (which is already attached to mlflow). 
When there is no custom header provider specified by the user, my singleton acts as no-op from the perspective of the mlflow library (the `in_context` returns false, which means that headers will not be taken from my implementation).

Hope that makes sense. You can feel free to take the code from the Kedro-VertexAI plugin and port it here, I will remove it from our plugin afterwards.

**Comment by Galileo-Galilei** [comment]
I've read your code carefully and I took some time to understand the inner details, but I think I've got the main idea. 

Basically, the only think to port to kedro-mlflow would be the singleton ``DynamicMLFlowRequestHeaderProvider()``, and we should find a way to inject the custom class through mllfow yaml, but it seems easy. I just don't understand why it would be better than the above solution with  ``_request_header_provider_registry``? It seems simpler and easier to maintain, even if not recommended (but the singleton pattern is dangerous too)

**Comment by marrrcin** [comment]
I didn't say anywhere that using private `_request_header_provider_registry` was better option. First I've discovered that it was one of the possible options, then I've created this GH issue and then I've found out a better way (with singleton) and implemented it. The singleton method is preferred here.

**Comment by Galileo-Galilei** [comment]
Hi @marrrcin, I finally ended up implemnting the first solution (append to mlflow private global variable), because I think it will end up with much less maintenance on my side and it seems reasonably stable even if it is private. I still think that it would be great to open an issue (or even a PR) in the mlflow to ask for a public method (``register_request_header_provider(MyCustomRHP)`` ?) to do so. 

Can you test if it works for you?
1. Install the dev branch
```bash 
pip uninstall kedro-mlflow
pip install git+https://github.com/Galileo-Galilei/kedro-mlflow@357-add-support-for-authorization-with-expiring-tokens
```

2. Update mlflow.yml

```yaml
#mlflow.yml
server: 
    mlflow_tracking_uri: ...
    credentials: null
    request_header_provider_class: path.to.your.module.YourCustomClass
```

3. Run it and see if it works!

I'll merge and release once I get your feedback on it.

**Comment by marrrcin** [comment]
Thanks for implementing this!
How will you pass additional configuration arguments to this class? Say I want to access kedro context / some config / just pure string value somehow from the request header provider? With this simple implementation (just passing the class) it's not possible. In my implementation, I've just passed the Kedro context and loaded params in the base implementation (`RequestHeaderProviderWithKedroContext`).

**Comment by marrrcin** [comment]
Ping @Galileo-Galilei 🙂

**Comment by Galileo-Galilei** [comment]
Hi @marrrcin, sorry I did not have time to finish this porperly, but i will take over within 1 week or two.

**Comment by Galileo-Galilei** [comment]
Hi @marrrcin, the MR should be ok, it just misses a little documentation. Would you mind trying it and tell me if it's ok for you? 

Install as explained above, and update your mlflow.yml as is (you can use ``kedro mlflow init --env=<your-env> --force``): 
```yaml
# mlflow.yml
server: 
    request_header_provider: 
        type: path.to.your.class
        pass_context: True # if you want to pass context. it must be named ``kedro_context`` in the ``__init__`` method of your custom ``request_header_provider``)
        init_kwargs: 
            a: 1
```

**Comment by marrrcin** [comment]
OK, I will check it out this week, thanks!

**Comment by Galileo-Galilei** [comment]
Hi @marrrcin, did you have time to test the implementation?

**Comment by marrrcin** [comment]
Sorry for the delay, but I've finally managed to test out your implementation - it works like a charm, great job! 💪🏻 
Looking forward to use it in our projects once you release it!
