### ISSUE TITLE
kedro mlflow ui gets a FileNotFoundError

### ISSUE THREAD

**Issue by Dopidotcsv** [Galileo-Galilei/kedro-mlflow#361]
Firstly I'd like to apologize if this is a dummy question.
I'm following the tutorial to get introduced to kedro mlflow,; after running the command "kedro mlflow init" I tried to run the command "kedro mlflofw ui" but I get an error:

INFO     The 'mlflow_tracking_uri' key in mlflow.yml is relative ('server.mlflow_tracking_uri = mlruns'). It is converted to a valid uri: 'file:///C:/Users/e107338/PycharmProjects/mlflow/kedro-mlflow-example/mlruns'                                                   kedro_mlflow_config.py:202

After the Traceback I get an error: FileNotFoundErrror

**Comment by Galileo-Galilei** [comment]
Hi, 

I am sorry to see you are experiencing issues. this is not a dummy question, it sounds like a bug. 

I've just ran this: 

```bash
conda create -n km-361 python=3.9 -y
conda activate km-361
pip install kedro==0.18.3
pip install mlflow==1.29.0
pip install kedro-mlflow==0.11.3
kedro new --starter=pandas-iris
cd iris
kedro mlflow init
kedro mlflow ui
```

then I opened ``http://127.0.0.1:5000`` and th UI opened as expected. 

Can you tell me: 
- your python version
- your OS
- your ``kedro`` / ``mlflow`` / ``kedro-mlflow`` version
- the project using
- the exact error message
- check if you have a ``MLFLOW_TRACKING_URI`` environment set

**Comment by Dopidotcsv** [comment]
It turned out fine  after trying again! Sorry and thanks for your consideration!
