### ISSUE TITLE
Logging artifact after pipeline ends

### ISSUE THREAD

**Issue by foxale** [Galileo-Galilei/kedro-mlflow#366]
## Description
Case is simple. We want to dump all logs to some log file during pipeline run, and always upload it at the very end as mlflow artifact.

## Context
You can see run's logs from mlflow UI.

## Possible Implementation
We couldn't find any kedro-mlflow-native way to do it, instead came up with multiple weird workarounds. 

The cleanest idea we had was to create a custom hook that would manually log the logging file to mlflow via `after_pipeline_run` hook. The problem was, that installed kedro plugins have priority over kedro plugins manually defined in  hooks.py, which meant kedro-mlflow's `after_pipeline_run` hook executed before ours and we ended up with duplicated mlflow entries. Our final solution (one that worked) was to use `@hookimpl(tryfirst=True)` for our hook, which would prioritize execution of our's hook over kedro-mlflow's. I guess an alternative solution here would be to use `@hookimpl(trylast=True)` for kedro-mlflow's hook, lowering its priority. 

## Possible Alternatives
Other than that, do you think there is any better way to do it? Our initial thoughts were to add this file to `catalog.yml` and use `after_context_created` or `after_catalog_created` or `before_pipeline_run` to somehow inject this entry to pipeline's datasets.

**Comment by Galileo-Galilei** [comment]
Hi @foxale, 

I dont under why the custom hook solutions ends up to duplicate logging? This seems the perfect solution. What do you log exactly? You don't have to configure anything since the plugin's hook executes before as you mention. Thisshould work as expected: 

```python
# custom_file.py
import mlflow
from kedro.framework.hooks import hook_impl

class CustomMlflowHook:
    @hook_impl
    def after_pipeline_run(
        self,
        run_params: Dict[str, Any],
        pipeline: Pipeline,
        catalog: DataCatalog,
    ) -> None:

         mlflow.log_artifact(r"logs/info.log")
```

```python
# setting.py
from custom_file import CustomMlflowHook

HOOKS=(CustomMlflowHook(),)
````

If it does not, can you tell me your exact setup? This is the best available solution so far I think.

**Comment by foxale** [comment]
We've had a similar setup but with:
```python
artifact = MlflowArtifactDataSet(
    data_set={ [...] }
)
artifact.save(data=self._read_pipeline_logs())
```
instead of `mlflow.log_artifact(r"logs/info.log")` and executed on two hooks: `after_pipeline_run` and `on_pipeline_error`.

The problem is `kedro-mlflow`'s hook are executed before this code and this hooks ends with: 
```            
# Close the mlflow active run at the end of the pipeline to avoid interactions with further runs
mlflow.end_run()
```
which, I assume, closes the first one run, and then our hook automatically creates the second run to upload the log file.

**Comment by Galileo-Galilei** [comment]
Hi @foxale, I've though a lot about your use case and can't came out with a better solution than the one suggested in above issue to force registering order:

```python
# settings.py
from kedro_mlflow.hooks import MLflowHooks  # I make these import up but you get the point
DISABLE_HOOKS_FOR_PLUGINS = ("kedro-mlflow",)
HOOKS = (MLflowHook(), YourHook(),)  # This is always a LIFO queue - in fact the LIFO order is inherit from `pytest` already
```

I suggest to close the issue, unless you find it does not solve your problem?

**Comment by foxale** [comment]
It did, thanks :)
