### ISSUE TITLE
Caching tensorflow model between inferences

### ISSUE THREAD

**Issue by mb1069** [Galileo-Galilei/kedro-mlflow#378]
I'm trying to serve a tensorflow model (~3MB as a pickle or .pb file), and it is being reloaded into a MemoryDataSet every time the inference pipeline is called. 

Is there a way of caching the model between executions to speed up this process?
I've tried using a CachedDataSet;

```classifier:
  type: CacheDataSet
  versioned: true
  dataset:
    type: tensorflow.TensorFlowModelDataset
    filepath: data/06_models/classifier
    layer: model 
```
But this causes an error.

In our API, the mlflow model containing our preprocessing+tensorflow pipeline is loaded as follows
`pipeline = mlflow.pyfunc.load_model(logged_model)`
and called using
`pipeline.predict(data)`

**Comment by Galileo-Galilei** [comment]
Hi @mb1069, nice to see you found the solution! 

Just in case, you can use 

```python
kpm_kwargs={
    'copy_mode': {"my_dataset_name": "assign"}
}
```
if you want to change only the copy for the "my_dataset_name" entry in your catalog. 

A bit off topic, but I'd be glad to have feedback on ``pipeline_ml_factory``: do you find it easy to use and understand? Is it convenient / useful?

**Comment by mb1069** [comment]
Hi Yolan,
I've found it very easy to use and adapt to my needs. The only feature I wish existed is an option to exclude nodes using a tag, but I think that's more of an issue for Kedro?

**Comment by Galileo-Galilei** [comment]
Sorry, I did not see your answer earlier, I don't know why. Glad to see you find it easy, I know many people struggle to understand its purpose. 

You can do something like ``my_pipeline.only_nodes_with_tags("my_tag")``, but AFAIK there is no ``my_pipeline.except_nodes_with_tags("my_tag")`` method in kedro. As you say, this is entirely related to kedro and not kedro-mlflow.
