### ISSUE TITLE
Cleanup for kedro==0.19

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#391]
## Description
This tickets gather breaking changes for ``kedro==0.19``:

- [x] rename all datasets without the capital S, e.g. ``MlflowArtifactData**S**et`` -> ``MlflowArtifactData**s**et`` -> done in #439 
- [x] rename ``MlflowModelSaverDataSet`` -> ``MlflowLocalModelDataSet`` (or ``MlflowModelLocalFileDataSet``?) and ``MlflowModelLoggerDataSet`` -> ``MlflowRemoteModelDataSet`` (or ``MlflowModelTrackingDataSet``?) To be discussed.
- [x] #479
- [x] #460
- [x] Add kedro-datasets as a dependency
- [x] #461
- [x] Change loops on ``catalog._data_sets`` to public attribute depending on kedro
- [x] Cleanup logging mocking in tests
- [x] remove support for python 3.7. this will enable to upgrade some dependencies (pre-commit, flake8, black,  isort)
- [ ] Deprecate ``ConfigLoader`` and ``TemplatedConfigLoader`` ans cleanup the codebase and tests, add ``OmegaConfigLoader`` instead
- [ ] Use __setattr__ to add mlflow config to the context in the ``after_context_created`` hook : https://github.com/Galileo-Galilei/kedro-mlflow/blob/845ad919c9dbd020e948e8adc2e0f9064de1ef68/kedro_mlflow/framework/hooks/mlflow_hook.py#L128-L131. This one is blocked by https://github.com/kedro-org/kedro/issues/1459.
- [ ] Undo https://github.com/Galileo-Galilei/kedro-mlflow/pull/453  : #480

**Comment by ShubhamZoro** [comment]
Assign this to me, please.

**Comment by Galileo-Galilei** [comment]
Hi @ShubhamZoro, sorry for the late reply! I'd love to assign this to you, but I think we should merge it to a develop branch because I may have a couple of release until 0.19 is released and I want to keep retrocompatibility.

**Comment by ShubhamZoro** [comment]
Do I need to change PickleDataset to PickleDataset or MemoryDataSet to MemoryDataset as well?
