### ISSUE TITLE
Option for using auto-generated names for kedro runs instead of pipeline name

### ISSUE THREAD

**Issue by AlexandreOuellet** [Galileo-Galilei/kedro-mlflow#426]
## Description
When running the same kedro pipeline multiple time in parallel (doing experiments in parallel), I would like an option to generate random name for those runs, instead of always having `__default__` or `pipelinename`

## Context
In my scenario, I have a lot of parameters to test, and I want to test them in parallel (1 kedro run per parameters), and I don't really care about an experiment name (although I do want to be able to refer to them quickly).  Instead of spending time naming my runs `pipelinename_flipr` and coming up with names and/or exposing the values there, I would like to simply have the run name be automatically generated (so that I can still refer to it in the future if needed).

## Possible Implementation
Have a setting in mlflow.tml's tracking->run to specify wether to use a predefined name (like it is currently) or to have a randomly generated run name.

## Possible Alternatives
Right now, I would need to modify mlflow.yml's tracking->run->name parameter for each run for each parameter values I would like to modify.

**Comment by Galileo-Galilei** [comment]
Hi, I agree such an option would be great! I thought that explictly writing:


```yaml
server: 
    tracking:
        run:
            name: null
```

but it uses "__default__" by default. I need to think about the best syntax since I guess this is the best default but I agree ``kedro-mlflow`` should support your use case.

**Comment by Galileo-Galilei** [comment]
Note for myself: I have found a way to make this possible and consistent with the interactive workflow (which is the hardest part): I'll create a custom resolver which will import the [``_generate_string``](https://stackoverflow.com/questions/76053273/how-can-i-set-the-seed-that-mlflow-uses-to-randomly-generate-run-names) from mlflow. 

I'll add this after 0.19 is officically out.

**Comment by Galileo-Galilei** [comment]
> I would love to see this merged. Any way I can help?

Sorry for the late reply. I had little time recently + there is a very subtle bug in hiw kedro handles resolver that needs to be addressed on the  core framework side, but I release this feature since the bug should very likely be hardly noticeable, and this is a commonly required feature.

**Comment by Galileo-Galilei** [comment]
Thanks!
This is already on PyPI, you can try with ``kedro-mlflow==0.12.1``>

For the record the syntax is :

```yaml
#mlflow.yml
tracking: 
    run: 
        name: ${km.random_name:} # don't forget the trailing ":" at the end ! 
```
