### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by rxm7706** [Galileo-Galilei/kedro-mlflow#449]
https://github.com/Galileo-Galilei/kedro-mlflow/blob/0d1a27257857bbaa3918d8b72f9e3159411a5557/setup.py#L78

Hi @Galileo-Galilei 
Since Kedro, Kedro-Datasets and Kedro-viz now support Python 3.11 ; it would be beneficial to start python 3.11 support for Kedro-MLFlow
Thanks

**Comment by Galileo-Galilei** [comment]
I am pretty sure it should already work. Would you mind opening this PR? I think we can remove the upper bound on python in ``setup.py``: 

https://github.com/Galileo-Galilei/kedro-mlflow/blob/master/setup.py#L34

and check if all tests pass.
