### ISSUE TITLE
package kedro-mlflow with wheel

### ISSUE THREAD

**Issue by Debbby57** [Galileo-Galilei/kedro-mlflow#515]
## Description
Hello Galileo,

First, thanks for your package ! I am not familiar with issue, sorry if it doesn't write correctly !

Can you build your package instead of providing only sources please ? I encountered a problem : in my local I have kedro-mlflow 0.11.8 which has been build with wheel 0.41.3, and when I deployed my project in kubernetes, when I retrieve kedro-mlflow 0.11.8, it has been build with wheel 0.42.0. The both versions don't create the same METADATA : 
in 0.41.3 : METADATA > Name: kedro-mlflow
in 0.42.0 : METADATA > Name: kedro_mlflow

## Context

This change resulted in `DISABLE_HOOKS_FOR_PLUGINS` no longer working in kedro settings. Indeed I had `DISABLE_HOOKS_FOR_PLUGINS = ("kedro-mlflow")` and I have to change it in `DISABLE_HOOKS_FOR_PLUGINS = ("kedro_mlflow")` because kedro use this package name to disable hooks.

I find a little bit annoying to depend on wheel version while it's the same version package :(

## Steps to Reproduce

1. create a conda environment with python 3.10.6 and wheel 0.42.0
2. pip install kedro-mlflow 0.11.8 (please be careful with your cache pip... you have to delete it)
3. check your METADATA file in the environment env/lib/python3.10/site-packages/kedro_mlflow-0.11.8.dist-info. It whill have `Name: kedro_mlflow` and the WHEEL file should have `Generator: bdist_wheel (0.42.0)`

4. create another conda environment with python 3.10.6 and wheel 0.41.3
5. pip install kedro-mlflow 0.11.8 (please be careful with your cache pip... you have to delete it)
6. check your METADATA file in the environment env/lib/python3.10/site-packages/kedro_mlflow-0.11.8.dist-info. It whill have `Name: kedro-mlflow` and the WHEEL file should have `Generator: bdist_wheel (0.41.3)`

## Expected Result

when I pip install kedro-mlflow=0.11.8 I want the same package name nevermind my environment.

Thanks four your help

**Comment by Galileo-Galilei** [comment]
Incredibly weird bug! I'll change the github action to publish wheel, thank you for the bug report!

**Comment by Debbby57** [comment]
thank you !
