### ISSUE TITLE
Add auto registration of model artifacts

### ISSUE THREAD

**Issue by mck-star-yar** [Galileo-Galilei/kedro-mlflow#550]
## Description

As a user I'd like to have an option to automatically register the model in mlflow, specifically PipelineML.

## Context

The current workflow of model development is DS runs pipeline -> inference part gets captured by Mlflow -> manual registration of the model in the model registry -> inference pipeline uses latest model from model registry. We'd like to make the manual process automatic.

## Possible Implementation

When defining the inference pipeline via `pipeline_ml_factory`, users can specify if they'd like this pipeline to be auto-registered in the model registry and the name of the model. Then we store that as an attribute in the PipelineML. And then hook will check this attribute and register the requested models.

The same can be done for the models defined via catalog – an extra parameter for registering the model and the name.

**Comment by mck-star-yar** [comment]
After researching this issue I came to understanding that this can be done by utilizing `log_model_kwargs` by passing `registered_model_name` to it.

**Comment by Galileo-Galilei** [comment]
Yes I was going to suggest to use log_model_kwargs but I did not remembered the exact settings, glad you find it by yourself. I reopen the issue to add it to the documentation.
