### ISSUE TITLE
No module named 'mlflow.utils.name_utils'

### ISSUE THREAD

**Issue by lvijnck** [Galileo-Galilei/kedro-mlflow#571]
## Description

After installation, getting the following error on `kedro run`

```
An error has occurred: No module named 'mlflow.utils.name_utils'  cli.py:212
```

## Context

Unable to run Kedro project after installation

## Steps to Reproduce

```
# Install ml flow
pip install kedro-mlflow
```

## Expected Result

Pipeline runs

## Actual Result

Pipeline fails

## Your Environment

* `kedro` and `kedro-mlflow` version used (`pip show kedro` and `pip show kedro-mlflow`): 0.19.7 and 0.12.2
* Python version used (`python -V`): Python 3.11.9
* Operating system and version: Mac

**Comment by lvijnck** [comment]
Not sure what happened here, I'm using `uv` to resolve dependencies and it looked like it installed an outdated mlflow version.

Pinned them in my requirements file for now.

```
kedro-mlflow==0.12.2
mlflow==2.15.0
```

**Comment by Galileo-Galilei** [comment]
Do you know which version was installed? Maybe I should pin a upper version of the lower bound of mlflow in the package, but there is likely little I can do.

**Comment by Galileo-Galilei** [comment]
The module was introduced in ``mlflow==1.29.0`` and I use it since #481. I've update the requirements to make supported version explicit. Thanks for notifying!
