### ISSUE TITLE
Investigate why support for modern kedro datasets breaks for kedro<0.19.7

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#592]
## Description

#590 introduced support for modern kedro datasets, i.e. with ``load`` and ``save`` defined on user side instead of private ``_load`` and ``_save``. This breaks my tests locally for ``kedro<0.19.7`` 

FYI @deepyaman, I'll take a stab at it. 

## Context

I should ensure retrocompatiblity, and this change isn't

## Steps to Reproduce

Install the last version of master , install kedro <0.19.7, run tests. 

## Actual Result

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment

* `kedro` and `kedro-mlflow` version used (`pip show kedro` and `pip show kedro-mlflow`):
* Python version used (`python -V`):
* Operating system and version:

**Comment by deepyaman** [comment]
@Galileo-Galilei Do you have a stack trace handy, by chance? The only thing I can imagine is if `super().save` and `super().load` aren't defined/raise attribute error, in which case may need the if condition to be `if hasattr(super(), "save") and ...`, etc.

**Comment by Galileo-Galilei** [comment]
There is an "obvious" (after 1 hour of debugging >< ) error in the code : [This line]( https://github.com/Galileo-Galilei/kedro-mlflow/blob/ed43e0dd1e7cd6ea24c9a5a9936c86435eb326b2/kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py#L140) misses a return statement and for the old dataset style, it leads to return  ``None`` when loading. 

I am a bit worried that is was not caught by [this test](https://github.com/Galileo-Galilei/kedro-mlflow/blob/ed43e0dd1e7cd6ea24c9a5a9936c86435eb326b2/tests/io/artifacts/test_mlflow_artifact_dataset.py#L335-L372) in the first place :confused:

**Comment by deepyaman** [comment]
> There is an "obvious" (after 1 hour of debugging >< ) error in the code : [his line](https://github.com/Galileo-Galilei/kedro-mlflow/blob/ed43e0dd1e7cd6ea24c9a5a9936c86435eb326b2/kedro_mlflow/io/artifacts/mlflow_artifact_dataset.py#L140) misses a return statement and for the old dataset style, it leads to return `None` when loading.

Gah, sorry!!

**Comment by Galileo-Galilei** [comment]
No problem, I didn't see it either!
