### ISSUE TITLE
Migrate to 0.16.5

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#62]
The 0.16.5 release is just out and comes with good and bad news: 
- [ ] Many tests are broken (for pipeline_ml, hook and template) and should be fixed ASAP. However, I think we can release all the functionalities we've worked on in the past month to make them available in a 0.3.0 release, and plan to migrate after this.
- [X] ~The [new way to register the config_loader, the pipeline and the catalog](https://github.com/quantumblacklabs/kedro/blob/f9100f85e4bd5326af4f3574839f618b33b76b5e/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/hooks.py#L43) make them accessible in a global [_hook_manager variable instantiated by get_hook_manager()](https://github.com/quantumblacklabs/kedro/blob/f9100f85e4bd5326af4f3574839f618b33b76b5e/kedro/framework/hooks/manager.py#L51). This enable us to change [get_mlflow_config()](https://github.com/Galileo-Galilei/kedro-mlflow/blob/404da2844964c4454377cf55d71f8ac48d1443b6/kedro_mlflow/framework/context/mlflow_context.py#L11) which currently:~ 
    - ~depends heavily on the template, and can only be called when the current working directory is the root of the kedro project. Indeed, when we call this function inside a hook we have no way to access the project path except by reading the `.kedro.yml`, but this requires knowing in advance where it is. Thanks to this change, we will be able to access the ConfigLoader instantiated in the ProjectContext inside the hook. This is directly related to this issue: quantumblacklabs/kedro#506, and it will enable to fix #30 which is particularly annoying but could not be fixed before this change.~
    - ~break supercharging of config loader by a user (which is quite common for people using [TemplatedConfigLoader](https://kedro.readthedocs.io/en/0.16.4/kedro.config.TemplatedConfigLoader.html) who are not able to use their customisation within the "mlflow.yml" file).~
- [ ] Update the `kedro mlflow init` command according to this new template. Should it write in the `run.py` `ProjectContext` class or in the `kedro.yml` `hooks` key?

**Comment by Galileo-Galilei** [comment]
Does anyone wants to take this one? @kaemo @akruszewski @takikadiri?

**Comment by kaemo** [comment]
@Galileo-Galilei I could work on this one next week.

**Comment by Galileo-Galilei** [comment]
Yes, sure. Do you plan to finish #56 first? I updated the [milestones](https://github.com/Galileo-Galilei/kedro-mlflow/milestones) to give visibility to what we prioritize (accordingly to what discussed), but feel free to move it to next release if you're not good to go yet.

**Comment by kaemo** [comment]
@Galileo-Galilei I've got #56 mostly done so I'll finish it first.

**Comment by takikadiri** [comment]
Almost all kedro_mlflow features and their tests are now working/passing on kedro 0.16.5, except `kedro mlflow init` because of the `run.py` update part.
