### ISSUE TITLE
Make mlflow init work when configuration is in pyproject.toml

### ISSUE THREAD

**Issue by Galileo-Galilei** [Galileo-Galilei/kedro-mlflow#96]
## Description

Since 0.16.5, kedro project can [now be configured with a `pyproject.toml` config file](https://github.com/quantumblacklabs/kedro/issues/439) instead of a `.kedro.yml` at the root of the projects. This breaks the `kedro mlflow init` command which is only compatible with `.kedro.yml` configuration file.

## Context
We should remove the `_get_project_globals` util function in kedromlflow and use `kedro.framework.context import get_static_project_data` as suggested in #86. **Beware: this will break retrocompatibilty and work only with kedro>=0.16.5**

## Steps to Reproduce

Launch `kedro mlflow init` with no `.kedro.yml` config file in your project but a valid `pyproject.toml`.

## Expected Result
The mlflow.yml file should be created

## Actual Result
An error is raised.

**Comment by takikadiri** [comment]
Well spoted ! We can already solve this, by bundling kedro's `get_static_project_data` inside kedro_mlflow as long as we keep kedro < 0.16.5 retrocompatibility. We can switch then to `kedro.framework.context import get_static_project_data` when we drop this compatibility in the futur. I can add it to [Migrate 0.16.5 pull request](https://github.com/Galileo-Galilei/kedro-mlflow/pull/94)

**Comment by Galileo-Galilei** [comment]
Ok let's do this!
